EU-OSHA/campaigns

docroot/sites/all/modules/osha/feeds/feeds.features.inc
docroot/sites/all/modules/osha/feeds/feeds.info
docroot/sites/all/modules/osha/feeds/feeds.module
docroot/sites/all/modules/osha/feeds/feeds.views_default.inc
drush/drushrc.php

added a view called Latest items that contains 2 RSS feeds
- Latest News
- Latest Events

news and events rss

---

docroot/sites/all/modules/osha/osha_events/osha_events.features.fe_block_settings.inc
docroot/sites/all/modules/osha/osha_events/osha_events.info
docroot/sites/all/modules/osha/osha_events/osha_events.module
docroot/sites/all/modules/osha/osha_events/theme/events_links.tpl.php
docroot/sites/all/themes/hwc_frontend/template.php

Still needs some CSS modifications

HCW-388-events-blocks Blocks order and page title for Events

---

docroot/sites/all/themes/hwc_frontend/templates/node--165--full.tpl.php

Am mai facut un template pentru node/165, dar nu imi dau seama prea bine ce se schimba in respectiva pagina, ca class container tot ramane, la fel ca si la node/184 tpl.

Hcw 408 delete container

---

docroot/sites/all/modules/osha/osha_newsletter/osha_newsletter.module
docroot/sites/all/themes/hwc_frontend/template.php

Din imaginea Newsletter-changes-20151013.png care este atasata tichetului:
- la punctul 2 nu apare acel paragraf
- la punctul 5 apare data cand s-a trimis respectivul newsletter, daca s-a trimis

HCW-596 newsletter design changes

---

docroot/sites/all/modules/hwc/hwc_partner/hwc_partner.info
docroot/sites/all/modules/hwc/hwc_partner/hwc_partner.pages_default.inc

Commit pentru HCW-865 si HCW-861

HCW-865 Partners Panels Breadcrumb

---

docroot/partner/forms/classes/CDB.php

CDBUpdateModification

---

docroot/partner/forms/config/cdb.json
docroot/partner/forms/mvc/view/tpl/html/html_header.html

Changes For PRO

---

docroot/partner/forms/mvc/view/js/scripts.js

Hidden Loader and display iframe

Hidden Loader and display iframe

---

docroot/partner/forms/mvc/view/js/scripts.js

Fix Loader Issue

---

docroot/partner/forms/mvc/controller/Dispatcher.php
docroot/partner/forms/mvc/controller/entities/Sidebar.php
docroot/partner/forms/mvc/view/css/style.css
docroot/partner/forms/mvc/view/js/scripts.js
docroot/partner/forms/mvc/view/tpl/html/header.html
docroot/partner/forms/mvc/view/tpl/widgets/image.html

MF iframe change + HWCCDB-362 + HWCCDB-315

MF iframe change + HWCCDB-362 + HWCCDB-315

---

docroot/partner/forms/mvc/view/js/scripts.js

HWCCDB-371

---

docroot/partner/forms/classes/CDB.php
docroot/partner/forms/mvc/controller/Controller.php
docroot/partner/forms/mvc/model/entities/mp_contact
docroot/partner/forms/mvc/model/entities/mp_involvement
docroot/partner/forms/mvc/model/entities/ocp_contact
docroot/partner/forms/mvc/model/entities/ocp_involvement
docroot/partner/forms/mvc/view/js/scripts.js
docroot/partner/forms/mvc/view/tpl/entities/sidebar.html

HWCCDB-68 HWCCDB-334

---

docroot/partner/forms/mvc/model/entities/mp_involvement
docroot/partner/forms/mvc/view/js/scripts.js
docroot/partner/forms/mvc/view/tpl/widgets/radio.html

HWCCDB-396, HWCCDB-393, HWCCDB-391

HWCCDB-396, HWCCDB-393, HWCCDB-391

---

docroot/partner/forms/classes/CDB.php
docroot/partner/forms/mvc/controller/Controller.php
docroot/partner/forms/mvc/model/entities/mp_involvement
docroot/partner/forms/mvc/view/css/bootstrap.css
docroot/partner/forms/mvc/view/css/bootstrap.min.css
docroot/partner/forms/mvc/view/css/style.css
docroot/partner/forms/mvc/view/js/scripts.js
docroot/partner/forms/mvc/view/tpl/entities/sidebar.html
docroot/partner/forms/mvc/view/tpl/html/footer.html
docroot/partner/forms/mvc/view/tpl/widgets/checkbox.html

Issues 2 Marzo

---

docroot/partner/forms/mvc/controller/Controller.php

Countries of activity issue

---

docroot/partner/forms/mvc/view/css/style.css
docroot/partner/forms/mvc/view/js/scripts.js
docroot/partner/forms/mvc/view/tpl/html/header.html

Issues 3 Marzo

---

docroot/partner/forms/mvc/controller/Controller.php
docroot/partner/forms/mvc/controller/entities/Sidebar.php
docroot/partner/forms/mvc/model/entities/fop_involvement
docroot/partner/forms/mvc/model/entities/mp_involvement
docroot/partner/forms/mvc/view/css/style.css
docroot/partner/forms/mvc/view/js/scripts.js
docroot/partner/forms/mvc/view/tpl/entities/fop_involvement.html
docroot/partner/forms/mvc/view/tpl/entities/mp_involvement.html
docroot/partner/forms/mvc/view/tpl/entities/ocp_contact.html

Critical Issues 3Marzo

---

docroot/partner/forms/mvc/controller/Controller.php

Social Networks for MF

---

docroot/partner/forms/mvc/view/js/scripts.js

Loader issue Deploy

---

docroot/partner/forms/mvc/model/entities/mp_involvement
docroot/partner/forms/mvc/view/css/print.css
docroot/partner/forms/mvc/view/css/style.css
docroot/partner/forms/mvc/view/js/scripts.js
docroot/partner/forms/mvc/view/tpl/entities/fop_company.html
docroot/partner/forms/mvc/view/tpl/entities/fop_contact.html
docroot/partner/forms/mvc/view/tpl/entities/mp_company.html
docroot/partner/forms/mvc/view/tpl/entities/mp_contact.html
docroot/partner/forms/mvc/view/tpl/entities/mp_involvement.html
docroot/partner/forms/mvc/view/tpl/entities/ocp_company.html
docroot/partner/forms/mvc/view/tpl/entities/ocp_contact.html
docroot/partner/forms/mvc/view/tpl/entities/sidebar.html

HWCCDB-402,  HWCCDB-424

---

docroot/partner/forms/mvc/view/js/scripts.js

Issue Print-Friendly+Save

---

docroot/partner/forms/classes/CDB.php

HWCCDB-435

---

docroot/partner/forms/mvc/controller/entities/Sidebar.php
docroot/partner/forms/mvc/view/css/print.css

HWCCDB-417 & printFriendly Issue

HWCCDB-417 & printFriendly Issue

---

docroot/partner/forms/classes/CDB.php
docroot/partner/forms/mvc/model/Model.php
docroot/partner/forms/mvc/model/entities/ocp_company
docroot/partner/forms/mvc/view/js/scripts.js
docroot/partner/forms/mvc/view/tpl/html/header.html

HWCCDB-388, HWCCDB-418, HWCCDB-335

HWCCDB-388, HWCCDB-418, HWCCDB-335

---

docroot/partner/forms/mvc/model/entities/fop_company

Issue homepage FOP MP

---

docroot/partner/forms/classes/CDB.php
docroot/partner/forms/mvc/controller/Controller.php
docroot/partner/forms/mvc/model/entities/mp_company
docroot/partner/forms/mvc/model/entities/mp_contact
docroot/partner/forms/mvc/model/entities/mp_involvement
docroot/partner/forms/mvc/model/entities/ocp_company
docroot/partner/forms/mvc/model/entities/ocp_contact
docroot/partner/forms/mvc/model/entities/ocp_involvement
docroot/partner/forms/mvc/view/css/style.css
docroot/partner/forms/mvc/view/js/scripts.js
docroot/partner/forms/mvc/view/tpl/entities/mp_company.html
docroot/partner/forms/mvc/view/tpl/entities/mp_contact.html
docroot/partner/forms/mvc/view/tpl/entities/mp_involvement.html
docroot/partner/forms/mvc/view/tpl/entities/ocp_company.html
docroot/partner/forms/mvc/view/tpl/entities/ocp_contact.html
docroot/partner/forms/mvc/view/tpl/entities/ocp_involvement.html
docroot/partner/forms/mvc/view/tpl/html/header.html

HWCCDB-453, HWCCDB-412, HWCCDB-331, HWCCDB-448

HWCCDB-453, HWCCDB-412, HWCCDB-331, HWCCDB-448

---

docroot/partner/forms/mvc/controller/Controller.php

HWCCDB-459

---

docroot/partner/forms/mvc/view/tpl/entities/congrats.html

HWCCDB-460

---

docroot/partner/forms/classes/CDB.php
docroot/partner/forms/mvc/controller/Dispatcher.php

CRM-PHP: Potential and Leads: Main contact change should not be
available for Leads in 'Invitation sent' status

HWCCDB-478

---

docroot/partner/forms/classes/CDB.php
docroot/partner/forms/mvc/controller/Controller.php
docroot/partner/forms/mvc/model/entities/mp_contact
docroot/partner/forms/mvc/model/entities/ocp_contact
docroot/partner/forms/mvc/view/js/scripts.js
docroot/partner/forms/mvc/view/tpl/widgets/contact_change.html

HWCCDB-444, HWCCDB-478 y OrgName error in IE

HWCCDB-444, HWCCDB-478 y OrgName error in IE

---

docroot/partner/forms/mvc/view/css/style.css
docroot/partner/forms/mvc/view/js/scripts.js
docroot/partner/forms/mvc/view/tpl/entities/fop_contact.html
docroot/partner/forms/mvc/view/tpl/entities/mp_contact.html
docroot/partner/forms/mvc/view/tpl/entities/ocp_contact.html
docroot/partner/forms/mvc/view/tpl/widgets/combined_checkbox.html

HWCCDB-215, HWCCDB-338, HWCCDB-220, HWCCDB-214, HWCCDB-213, HWCCDB-211,
HWCCDB-210, HWCCDB-209, HWCCDB-129

Responsive design issues

---

docroot/partner/forms/mvc/view/css/style.css

Updated breakpoints media queries and some styles due to iframe´s CSS
container rules.

Responsive design issues iframe

---

docroot/partner/forms/mvc/model/entities/mp_company
docroot/partner/forms/mvc/model/entities/ocp_company
docroot/partner/forms/mvc/view/js/scripts.js
docroot/partner/forms/mvc/view/tpl/entities/mp_company.html
docroot/partner/forms/mvc/view/tpl/entities/ocp_company.html

PHP - CEO change - As with main contact, include the checkbox to change
the CEO or Editor in chief in Maintenance forms (OCPs and MPs)

HWCCDB-482

---

docroot/partner/forms/classes/CDB.php

Added file CDB.php class to the release

CDB ceo_changed fixed

---

docroot/partner/forms/mvc/view/tpl/widgets/contact_change.html

Contact_change widget changes added to release

HWCCDB-482 Contact_change widget changes

---

docroot/sites/all/modules/osha/osha_newsletter/osha_newsletter.install

MDR-856 - fr for newsletter
